server:
  address: 0.0.0.0
  port: 8106
  servlet:
    context-path: /api/judge
    session:
      cookie:
        max-age: 2592000
        path: /api
spring:
  application:
    name: onlineJudge-backend-service-judge
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: classpath:rpc.yml,classpath:cache.yml,classpath:rabbitmq.yml

dubbo:
  application:
    qos-port: 9986

knife4j:
  enable: true