spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      global-cors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      routes:
        - id: onlineJudge-backend-service-user
          uri: lb://onlineJudge-backend-service-user
          predicates:
            - Path=/api/user/**
          filters:
            - AddRequestHeader=X-Forwarded-By, Service-Gateway
        - id: onlineJudge-backend-auth
          uri: lb://onlineJudge-backend-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - AddRequestHeader=X-Forwarded-By, Service-Gateway
        - id: onlineJudge-backend-service-captcha
          uri: lb://onlineJudge-backend-service-captcha
          predicates:
            - Path=/api/captcha/**
          filters:
            - AddRequestHeader=X-Forwarded-By, Service-Gateway
  application:
    name: @application.name@
  config:
    import: classpath:rpc.yml,classpath:config.yml
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  profiles:
    active: dev
server:
  port: 8100

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
      excluded-services:
        - .*?dubbo.*
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
#    reactor.netty: debug
    com.github.xiaoymin.knife4j: debug