spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      global-cors:
        cors-configurations:
          '[/**]':
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      routes:
        - id: onlineJudge-backend-service-user
          uri: lb://onlineJudge-backend-service-user
          predicates:
            - Path=/api/user/**
          filters:
            - AddRequestHeader=X-Forwarded-By, Service-Gateway
        - id: onlineJudge-backend-auth
          uri: lb://onlineJudge-backend-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - AddRequestHeader=X-Forwarded-By, Service-Gateway
        - id: onlineJudge-backend-service-captcha
          uri: lb://onlineJudge-backend-service-captcha
          predicates:
            - Path=/api/captcha/**
          filters:
            - AddRequestHeader=X-Forwarded-By, Service-Gateway
        - id: onlineJudge-backend-service-admin
          uri: lb://onlineJudge-backend-service-admin
          predicates:
            - Path=/api/admin/**
          filters:
            - AddRequestHeader=X-Forwarded-By, Service-Gateway
        - id: onlineJudge-backend-service-question
          uri: lb://onlineJudge-backend-service-question
          predicates:
            - Path=/api/question/**
          filters:
            - AddRequestHeader=X-Forwarded-By, Service-Gateway
        - id: onlineJudge-backend-service-judge
          uri: lb://onlineJudge-backend-service-judge
          predicates:
            - Path=/api/judge/**
  application:
    name: @application.name@
  config:
    import: classpath:rpc.yml,classpath:config.yml,classpath:cache.yml
  main:
    web-application-type: reactive
  profiles:
    active: dev
server:
  port: 8100

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
      excluded-services:
        - .*?dubbo.*
logging:
  level:
    org.springframework.cloud.gateway: debug  # 打印网关相关的详细信息
    org.springframework.http.server.reactive: debug  # 打印HTTP请求处理的详细信息
    org.springframework.web.reactive: debug  # 打印WebFlux的详细信息
    reactor.netty: debug  # 打印Netty的详细信息
    cn.dev33.satoken: debug  # 打印sa-token相关的日志
    com.github.xiaoymin.knife4j: debug  # 打印Knife4j的调试日志
    root: debug