server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api/user
    session:
      cookie:
        max-age: 2592000
        path: /api

spring:
  application:
    name: @application.name@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: classpath:rpc.yml,classpath:cache.yml,classpath:datasource.yml,classpath:email.yml,classpath:rabbitmq.yml

knife4j:
  enable: true

logging:
  level:
    web: debug

dubbo:
  application:
    qos-port: 9991

redis-session:
  instance:
    bloom-filter:
      host: 127.0.0.1
      port: 6379
      database: 5
      timeout: 5000

rabbitmq:
  exchanges:
    - name: emailExchange
      type: direct
      durable: true
      autoDelete: false
      bindings:
        - queue: emailQueue
          routingKey: email.active
          deadLetterRoutingKey: dl.email.captcha
          deadLetterQueue: X-DeadLetter-Email-Captcha-Queue
          durable: true
          autoDelete: false
          exclusive: false