server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api/user
    session:
      cookie:
        max-age: 2592000
        path: /api
spring:
  application:
    name: onlineJudge-backend-service-user
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  #  配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oj_sys
    username: root
    password: as123456789
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:9097

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true



dubbo:
  qos:
    port: 33333  # 选择一个未被使用的端口
    enable: true
  application:
    name: onlineJudge-backend-service-user
    qos-enable: true
    qos-port: 33333  # Change to an available port
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:9097
    parameters:
      namespace: f098c06f-48fc-44dd-88d8-09af7c71fb96
      group: dubbo
  protocol:
    name: dubbo
    port: 20881
logging:
  level:
    web: debug