server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/question
    session:
      cookie:
        max-age: 2592000
        path: /api
spring:
  application:
    name: onlineJudge-backend-service-question
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    import: classpath:rpc.yml,classpath:cache.yml,classpath:datasource.yml,classpath:email.yml,classpath:rabbitmq.yml


rabbitmq:
  exchanges:
    - name: questionExchange
      type: direct
      durable: true
      autoDelete: false
      bindings:
        - queue: judgeQuestionQueue
          routingKey: question.judge
          deadLetterRoutingKey: dl.question.judge
          deadLetterQueue: X-DeadLetter-Judge-Question-Queue
          durable: true
          autoDelete: false
          exclusive: false

dubbo:
  application:
    qos-port: 9997
knife4j:
  enable: true