spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000
      database: 0
  redis:
    redisson:
      enabled: true
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://127.0.0.1:6379"   #首次启动前务必修改成你自己的,并删除这段注解！！！
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 6
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
#redis-session:
#  instance:
#    lock:
#      host: 127.0.0.1
#      port: 6379
#      timeout: 5000
#      database: 3
#    limiter:
#      host: 127.0.0.1
#      port: 6379
#      timeout: 5000
#      database: 4