spring:
  application:
    name: @application.name@
  config:
    import: classpath:rpc.yml,classpath:cache.yml,classpath:saToken.yml
  profiles:
    active: dev

server:
  port: 7880
  servlet:
    context-path: /api/auth

dubbo:
  application:
    qos-port: 9990

knife4j:
  enable: true
